name: vyaa_central_infor_webflutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^7.0.0
  shared_preferences: ^2.1.1
  http: ^0.13.6
  flutter_svg: ^2.0.7
  get: ^4.7.2
  flutter_side_menu: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svg/
flutter_launcher_icons:
  web:
    generate: true
  image_path: "assets/icons/vyaa-solo-icon.png"
  adaptive_icon_background: "#ffffff"
