// <auto-generated />
using System;
using System.Collections.Generic;
using AVASphere.ApplicationCore.Common.Entities.General;
using AVASphere.ApplicationCore.Common.Entities.Jsons;
using AVASphere.ApplicationCore.Sales.Entities;
using AVASphere.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AVASphere.Infrastructure.System.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20251111170101_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdArea");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", b =>
                {
                    b.Property<int>("IdConfigSys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfigSys"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<ICollection<ColorsJson>>("Colors")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<ICollection<NotUseModuleJson>>("NotUseModules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdConfigSys");

                    b.ToTable("ConfigSys", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCustomer"));

                    b.Property<DirectionJson>("DirectionJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("DirectionJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("ExternalId");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<PaymentMethodsJson>("PaymentMethodsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentMethodsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<PaymentTermsJson>("PaymentTermsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentTermsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer")
                        .HasColumnName("PhoneNumber");

                    b.Property<SettingsCustomerJson>("SettingsCustomerJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("SettingsCustomerJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TaxId");

                    b.HasKey("IdCustomer")
                        .HasName("PK_Customers_IdCustomer");

                    b.HasIndex("DirectionJson")
                        .HasDatabaseName("IX_Customers_DirectionJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DirectionJson"), "gin");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_ExternalId");

                    b.HasIndex("SettingsCustomerJson")
                        .HasDatabaseName("IX_Customers_SettingsCustomerJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SettingsCustomerJson"), "gin");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("IX_Customers_TaxId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<int>("IdArea")
                        .HasColumnType("integer");

                    b.Property<List<Module>>("Modules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<Permission>>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdRol");

                    b.HasIndex("IdArea");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Aux")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreateAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Verified")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdConfigSys");

                    b.HasIndex("IdRol");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", b =>
                {
                    b.Property<int>("IdProjectCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProjectCategory"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdProjectCategory");

                    b.ToTable("ProjectCategory", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuotationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    b.Property<int>("Folio")
                        .HasColumnType("integer")
                        .HasColumnName("Folio");

                    b.Property<List<QuotationFollowupsJson>>("Followups")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("FollowupsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer")
                        .HasColumnName("IdConfigSys");

                    b.Property<string>("LinkedSaleFolio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LinkedSaleFolio");

                    b.Property<string>("LinkedSaleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LinkedSaleId");

                    b.Property<List<SingleProductJson>>("Products")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SaleDate");

                    b.PrimitiveCollection<List<string>>("SalesExecutives")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("SalesExecutives")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("QuotationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdConfigSys");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.QuotationVersion", b =>
                {
                    b.Property<int>("QuotationVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotationVersion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuotationVersionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("GeneralComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdQuotation")
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    b.Property<List<SingleProductJson>>("Products")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Quotation>("QuotationData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("QuotationData")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("VersionNumber");

                    b.HasKey("QuotationVersionId");

                    b.HasIndex("IdQuotation");

                    b.ToTable("QuotationVersions", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdSale");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("AfterSalesFollowupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AfterSalesFollowupDate");

                    b.Property<AuxNoteDataJson>("AuxNoteDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("AuxNoteDataJson");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SaleDate");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeliveryDate");

                    b.Property<string>("DeliveryDriver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DeliveryDriver");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Folio");

                    b.Property<bool>("HomeDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("HomeDelivery");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer")
                        .HasColumnName("IdConfigSys");

                    b.Property<List<QuotationReference>>("LinkedQuotations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("LinkedQuotationsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<List<SingleProductJson>>("Products")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("SalesExecutive")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SalesExecutive");

                    b.Property<int>("SatisfactionLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("SatisfactionLevel");

                    b.Property<string>("SatisfactionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SatisfactionReason");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdConfigSys");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.SaleQuotation", b =>
                {
                    b.Property<int>("IdSaleQuotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdSaleQuotation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSaleQuotation"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("CreatedBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdQuotation")
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    b.Property<int>("IdSale")
                        .HasColumnType("integer")
                        .HasColumnName("IdSale");

                    b.Property<PriceSnapshotJson>("PriceSnapshot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PriceSnapshotJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<List<SingleProductJson>>("Products")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdSaleQuotation");

                    b.HasIndex("IdQuotation");

                    b.ToTable("SaleQuotations", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", "Area")
                        .WithMany("Rol")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.User", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Users")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigSys");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Quotation", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Quotations_Customers_IdCustomer");

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Quotations")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Quotations_ConfigSys_IdConfigSys");

                    b.Navigation("ConfigSys");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.QuotationVersion", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Sales.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("IdQuotation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("QuotationVersion");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Sale", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sales_Customers_IdCustomer");

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Sales")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("IdConfigSys");

                    b.Navigation("ConfigSys");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.SaleQuotation", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Sales.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("IdQuotation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SaleQuotation_Quotation_IdQuotation");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", b =>
                {
                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("Sales");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Customer", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
