// <auto-generated />
using System;
using System.Collections.Generic;
using AVASphere.ApplicationCore.Common.Entities.Catalogs;
using AVASphere.ApplicationCore.Common.Entities.General;
using AVASphere.ApplicationCore.Common.Entities.Jsons;
using AVASphere.ApplicationCore.Common.Entities.Products;
using AVASphere.ApplicationCore.Projects.Entities.General;
using AVASphere.ApplicationCore.Projects.Entities.jsons;
using AVASphere.ApplicationCore.Sales.Entities;
using AVASphere.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AVASphere.Infrastructure.System.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdArea");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Property", b =>
                {
                    b.Property<int>("IdProperty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProperty"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdProperty");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.PropertyValue", b =>
                {
                    b.Property<int>("IdPropertyValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPropertyValue"));

                    b.Property<int?>("FatherValue")
                        .HasColumnType("integer");

                    b.Property<int>("IdProperty")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdPropertyValue");

                    b.HasIndex("FatherValue");

                    b.HasIndex("IdProperty");

                    b.ToTable("PropertyValue", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSupplier"));

                    b.Property<string>("BusinessId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<ContactsJson>("ContactsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ContactsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("CurrencyCoin")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("DeliveryDays")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<PaymentMethodsJson>("PaymentMethodsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentMethodsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<PaymentTermsJson>("PaymentTermsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentTermsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PersonType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdSupplier");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", b =>
                {
                    b.Property<int>("IdConfigSys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfigSys"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<ICollection<ColorsJson>>("Colors")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<ICollection<NotUseModuleJson>>("NotUseModules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdConfigSys");

                    b.ToTable("ConfigSys", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCustomer"));

                    b.Property<DirectionJson>("DirectionJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("DirectionJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("ExternalId");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<PaymentMethodsJson>("PaymentMethodsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentMethodsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<PaymentTermsJson>("PaymentTermsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PaymentTermsJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<SettingsCustomerJson>("SettingsCustomerJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("SettingsCustomerJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TaxId");

                    b.HasKey("IdCustomer")
                        .HasName("PK_Customers_IdCustomer");

                    b.HasIndex("DirectionJson")
                        .HasDatabaseName("IX_Customers_DirectionJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DirectionJson"), "gin");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_ExternalId");

                    b.HasIndex("SettingsCustomerJson")
                        .HasDatabaseName("IX_Customers_SettingsCustomerJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SettingsCustomerJson"), "gin");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("IX_Customers_TaxId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<int>("IdArea")
                        .HasColumnType("integer");

                    b.Property<List<Module>>("Modules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<Permission>>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdRol");

                    b.HasIndex("IdArea");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Aux")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("IdUser");

                    b.HasIndex("IdConfigSys");

                    b.HasIndex("IdRol");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<AuxDataJson>("AuxDataJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<ICollection<CategoriesJson>>("CategoriesJsons")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<ICollection<CodeJson>>("CodeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<ICollection<CostsJson>>("CostsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("integer");

                    b.Property<ICollection<ProductImageJson>>("ImageUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("MainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<ICollection<SolutionsJson>>("SolutionsJsons")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<double>("Taxes")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.ProductProperties", b =>
                {
                    b.Property<int>("IdProductProperties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProductProperties"));

                    b.Property<string>("CustomValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdPropertyValue")
                        .HasColumnType("integer");

                    b.HasKey("IdProductProperties");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdPropertyValue");

                    b.ToTable("ProductProperties", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.Inventory", b =>
                {
                    b.Property<int>("IdInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInventory"));

                    b.Property<int?>("IdPhysicalInventory")
                        .HasColumnType("integer");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("integer");

                    b.Property<double?>("LocationDetail")
                        .HasColumnType("double precision");

                    b.Property<string>("StatusInventoryProduct")
                        .HasColumnType("text");

                    b.Property<double>("Stock")
                        .HasColumnType("double precision");

                    b.Property<double>("StockMax")
                        .HasColumnType("double precision");

                    b.Property<double>("StockMin")
                        .HasColumnType("double precision");

                    b.HasKey("IdInventory");

                    b.HasIndex("IdPhysicalInventory");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.LocationDetails", b =>
                {
                    b.Property<int>("IdLocationDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocationDetails"));

                    b.Property<int>("IdArea")
                        .HasColumnType("integer");

                    b.Property<int>("IdStorageStructure")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VerticalLevel")
                        .HasColumnType("integer");

                    b.HasKey("IdLocationDetails");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdStorageStructure");

                    b.ToTable("LocationDetails", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventory", b =>
                {
                    b.Property<int>("IdPhysicalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhysicalInventory"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPhysicalInventory");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("PhysicalInventory", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventoryDetail", b =>
                {
                    b.Property<int>("IdPhysicalInventoryDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhysicalInventoryDetail"));

                    b.Property<double>("Difference")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdLocationDetails")
                        .HasColumnType("integer");

                    b.Property<int>("IdPhysicalInventory")
                        .HasColumnType("integer");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<double>("PhysicalQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("StatusInventoryProduct")
                        .HasColumnType("text");

                    b.Property<double>("SystemQuantity")
                        .HasColumnType("double precision");

                    b.HasKey("IdPhysicalInventoryDetail");

                    b.HasIndex("IdLocationDetails");

                    b.HasIndex("IdPhysicalInventory");

                    b.HasIndex("IdProduct");

                    b.ToTable("PhysicalInventoryDetail", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.StockMovement", b =>
                {
                    b.Property<int>("IdStockMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStockMovement"));

                    b.Property<int>("ByUser")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("integer");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("ReferenceType")
                        .HasColumnType("double precision");

                    b.Property<int?>("WarehouseIdWarehouse")
                        .HasColumnType("integer");

                    b.HasKey("IdStockMovement");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdWarehouse");

                    b.HasIndex("WarehouseIdWarehouse");

                    b.ToTable("StockMovement", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.StorageStructure", b =>
                {
                    b.Property<int>("IdStorageStructure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStorageStructure"));

                    b.Property<string>("CodeRack")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSubLevel")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdArea")
                        .HasColumnType("integer");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("integer");

                    b.Property<bool>("OneSection")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeStorageSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdStorageStructure");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("StorageStructure", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWarehouse"));

                    b.Property<double>("Active")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("IsMain")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdWarehouse");

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.WarehouseTransfer", b =>
                {
                    b.Property<int>("IdWarehouseTransfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWarehouseTransfer"));

                    b.Property<double>("IdWarehouseFrom")
                        .HasColumnType("double precision");

                    b.Property<double>("IdWarehouseTo")
                        .HasColumnType("double precision");

                    b.Property<string>("Observations")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TransferDate")
                        .HasColumnType("integer");

                    b.HasKey("IdWarehouseTransfer");

                    b.ToTable("WarehouseTransfer", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.WarehouseTransferDetail", b =>
                {
                    b.Property<int>("IdTransferDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransferDetail"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdWarehouseTransfer")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("TransferDate")
                        .HasColumnType("integer");

                    b.HasKey("IdTransferDetail");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdWarehouseTransfer");

                    b.ToTable("WarehouseTransferDetail", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", b =>
                {
                    b.Property<int>("IdProjectCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProjectCategory"));

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdProjectCategory");

                    b.HasIndex("IdConfigSys");

                    b.ToTable("ProjectCategory", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.IndividualListingProperties", b =>
                {
                    b.Property<int>("IdIndividualListingProperties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndividualListingProperties"));

                    b.Property<int>("IdIndividualProjectQuote")
                        .HasColumnType("integer");

                    b.Property<int>("IdProductProperties")
                        .HasColumnType("integer");

                    b.HasKey("IdIndividualListingProperties");

                    b.HasIndex("IdIndividualProjectQuote");

                    b.HasIndex("IdProductProperties");

                    b.ToTable("IndividualListingProperties", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.IndividualProjectQuote", b =>
                {
                    b.Property<int>("IdIndividualProjectQuote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndividualProjectQuote"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IdProjectCategory")
                        .HasColumnType("integer");

                    b.Property<int>("IdProjectQuotes")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("StatusProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("IdIndividualProjectQuote");

                    b.HasIndex("IdProjectCategory");

                    b.HasIndex("IdProjectQuotes");

                    b.ToTable("IndividualProjectQuote", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ListOfCategories", b =>
                {
                    b.Property<int>("IdListOfCategories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdListOfCategories"));

                    b.Property<int>("IdProject")
                        .HasColumnType("integer");

                    b.Property<int>("IdProjectCategory")
                        .HasColumnType("integer");

                    b.Property<SolutionsJson>("SolutionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("IdListOfCategories");

                    b.HasIndex("IdProject");

                    b.HasIndex("IdProjectCategory");

                    b.ToTable("ListOfCategories", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ListOfProductsToQuot", b =>
                {
                    b.Property<int>("IdListOfProductsToQuot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdListOfProductsToQuot"));

                    b.Property<int>("IdIndividualProjectQuotes")
                        .HasColumnType("integer");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.HasKey("IdListOfProductsToQuot");

                    b.HasIndex("IdIndividualProjectQuotes");

                    b.HasIndex("IdProduct");

                    b.ToTable("ListOfProductsToQuot", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.Project", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProject"));

                    b.Property<AppointmentJson>("AppointmentJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentHito")
                        .HasColumnType("integer");

                    b.Property<string>("ExactAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("integer");

                    b.Property<int>("IdProjectQuote")
                        .HasColumnType("integer");

                    b.Property<ICollection<VisitsJson>>("VisitsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("WrittenAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdProject");

                    b.HasIndex("IdConfigSys");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ProjectQuote", b =>
                {
                    b.Property<int>("IdProjectQuotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProjectQuotes"));

                    b.Property<double>("GrandTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("IdProject")
                        .HasColumnType("integer");

                    b.Property<double>("TotalTaxes")
                        .HasColumnType("double precision");

                    b.HasKey("IdProjectQuotes");

                    b.HasIndex("IdProject")
                        .IsUnique();

                    b.ToTable("ProjectQuote", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.TechnicalDesign", b =>
                {
                    b.Property<int>("IdTechnicalDesign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTechnicalDesign"));

                    b.Property<int>("IdProjectCategory")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SavedDesign")
                        .HasColumnType("text");

                    b.HasKey("IdTechnicalDesign");

                    b.HasIndex("IdProjectCategory");

                    b.ToTable("TechnicalDesign", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Quotation", b =>
                {
                    b.Property<int>("IdQuotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuotation"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Folio")
                        .HasColumnType("integer")
                        .HasColumnName("Folio");

                    b.Property<List<QuotationFollowupsJson>>("FollowupsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("FollowupsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer")
                        .HasColumnName("IdConfigSys");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    b.Property<string>("LinkedSaleFolio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LinkedSaleFolio");

                    b.Property<string>("LinkedSaleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LinkedSaleId");

                    b.Property<List<SingleProductJson>>("ProductsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("SaleDate");

                    b.PrimitiveCollection<List<string>>("SalesExecutives")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("SalesExecutives")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("IdQuotation");

                    b.HasIndex("IdConfigSys");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.QuotationVersion", b =>
                {
                    b.Property<int>("IdQuotationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotationVersion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuotationVersion"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("GeneralComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdQuotation")
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    b.Property<List<SingleProductJson>>("ProductsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<QuotationDataJson>("QuotationDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("QuotationDataJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("VersionNumber");

                    b.HasKey("IdQuotationVersion");

                    b.HasIndex("IdQuotation");

                    b.ToTable("QuotationVersions", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdSale");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSale"));

                    b.Property<DateTime?>("AfterSalesFollowupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AfterSalesFollowupDate");

                    b.Property<AuxNoteDataJson>("AuxNoteDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("AuxNoteDataJson");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeliveryDate");

                    b.Property<string>("DeliveryDriver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DeliveryDriver");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Folio");

                    b.Property<bool>("HomeDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("HomeDelivery");

                    b.Property<int>("IdConfigSys")
                        .HasColumnType("integer")
                        .HasColumnName("IdConfigSys");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("IdCustomer");

                    b.Property<List<QuotationReference>>("LinkedQuotations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("LinkedQuotationsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<List<SingleProductJson>>("ProductsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SaleDate");

                    b.Property<string>("SalesExecutive")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SalesExecutive");

                    b.Property<int?>("SatisfactionLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("SatisfactionLevel");

                    b.Property<string>("SatisfactionReason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("not specified")
                        .HasColumnName("SatisfactionReason");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdSale");

                    b.HasIndex("IdConfigSys");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.SaleQuotation", b =>
                {
                    b.Property<int>("IdSaleQuotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdSaleQuotation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSaleQuotation"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("GeneralComment");

                    b.Property<int>("IdQuotation")
                        .HasColumnType("integer")
                        .HasColumnName("IdQuotation");

                    b.Property<int>("IdSale")
                        .HasColumnType("integer")
                        .HasColumnName("IdSale");

                    b.Property<PriceSnapshotJson>("PriceSnapshot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("PriceSnapshotJson")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<List<SingleProductJson>>("ProductsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProductsJson")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("IdSaleQuotation");

                    b.HasIndex("IdQuotation");

                    b.HasIndex("IdSale");

                    b.ToTable("SaleQuotations", (string)null);
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.PropertyValue", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.PropertyValue", null)
                        .WithMany()
                        .HasForeignKey("FatherValue")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Property", "Property")
                        .WithMany("CatalogValue")
                        .HasForeignKey("IdProperty")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", "Area")
                        .WithMany("Rol")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.User", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Users")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigSys");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.Product", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Supplier", "Supplier")
                        .WithMany("Product")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.ProductProperties", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany("ProductProperties")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.PropertyValue", "PropertyValue")
                        .WithMany("ProductProperties")
                        .HasForeignKey("IdPropertyValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PropertyValue");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.Inventory", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventory", "PhysicalInventory")
                        .WithMany("Inventories")
                        .HasForeignKey("IdPhysicalInventory")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhysicalInventory");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.LocationDetails", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.StorageStructure", "StorageStructure")
                        .WithMany("LocationDetails")
                        .HasForeignKey("IdStorageStructure")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("StorageStructure");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventory", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", "Warehouse")
                        .WithMany("PhysicalInventories")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventoryDetail", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.LocationDetails", "LocationDetails")
                        .WithMany("PhysicalInventoryDetails")
                        .HasForeignKey("IdLocationDetails")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventory", "PhysicalInventory")
                        .WithMany("PhysicalInventoryDetails")
                        .HasForeignKey("IdPhysicalInventory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationDetails");

                    b.Navigation("PhysicalInventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.StockMovement", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", null)
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseIdWarehouse");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.StorageStructure", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", "Warehouse")
                        .WithMany("StorageStructures")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.WarehouseTransferDetail", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Inventory.Entities.General.WarehouseTransfer", "WarehouseTransfer")
                        .WithMany("WarehouseTransferDetails")
                        .HasForeignKey("IdWarehouseTransfer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WarehouseTransfer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("ProjectCategories")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigSys");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.IndividualListingProperties", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.General.IndividualProjectQuote", "IndividualProjectQuote")
                        .WithMany("IndividualListingProperties")
                        .HasForeignKey("IdIndividualProjectQuote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.ProductProperties", "ProductProperties")
                        .WithMany("IndividualListingProperties")
                        .HasForeignKey("IdProductProperties")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IndividualProjectQuote");

                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.IndividualProjectQuote", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", "ProjectCategory")
                        .WithMany("IndividualProjectQuotes")
                        .HasForeignKey("IdProjectCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.General.ProjectQuote", "ProjectQuote")
                        .WithMany("IndividualProjectQuotes")
                        .HasForeignKey("IdProjectQuotes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCategory");

                    b.Navigation("ProjectQuote");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ListOfCategories", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.General.Project", "Project")
                        .WithMany("ListOfCategories")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", "ProjectCategory")
                        .WithMany("ListOfCategories")
                        .HasForeignKey("IdProjectCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectCategory");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ListOfProductsToQuot", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.General.IndividualProjectQuote", "IndividualProjectQuotes")
                        .WithMany("ListOfProductsToQuot")
                        .HasForeignKey("IdIndividualProjectQuotes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IndividualProjectQuotes");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.Project", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Projects")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigSys");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ProjectQuote", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.General.Project", "Project")
                        .WithOne("ProjectQuote")
                        .HasForeignKey("AVASphere.ApplicationCore.Projects.Entities.General.ProjectQuote", "IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.TechnicalDesign", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", "ProjectCategory")
                        .WithMany("TechnicalDesigns")
                        .HasForeignKey("IdProjectCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("AVASphere.ApplicationCore.Projects.Entities.jsons.SolutionsJson", "SolutionsJsons", b1 =>
                        {
                            b1.Property<int>("TechnicalDesignIdTechnicalDesign")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Index")
                                .HasColumnType("integer")
                                .HasColumnName("SolutionsJsons_Index");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("SolutionsJsons_Name");

                            b1.Property<string>("NormalizedName")
                                .HasColumnType("text")
                                .HasColumnName("SolutionsJsons_NormalizedName");

                            b1.HasKey("TechnicalDesignIdTechnicalDesign", "__synthesizedOrdinal");

                            b1.ToTable("TechnicalDesign");

                            b1.ToJson("SolutionsJsons");

                            b1.WithOwner()
                                .HasForeignKey("TechnicalDesignIdTechnicalDesign");
                        });

                    b.Navigation("ProjectCategory");

                    b.Navigation("SolutionsJsons");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Quotation", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Quotations")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Quotations_ConfigSys_IdConfigSys");

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Quotations_Customers_IdCustomer");

                    b.Navigation("ConfigSys");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.QuotationVersion", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Sales.Entities.Quotation", "Quotation")
                        .WithMany("Versions")
                        .HasForeignKey("IdQuotation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("QuotationVersion");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Sale", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", "ConfigSys")
                        .WithMany("Sales")
                        .HasForeignKey("IdConfigSys")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("IdConfigSys");

                    b.HasOne("AVASphere.ApplicationCore.Common.Entities.General.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sales_Customers_IdCustomer");

                    b.Navigation("ConfigSys");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.SaleQuotation", b =>
                {
                    b.HasOne("AVASphere.ApplicationCore.Sales.Entities.Quotation", "Quotation")
                        .WithMany("SaleQuotations")
                        .HasForeignKey("IdQuotation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SaleQuotation_Quotation_IdQuotation");

                    b.HasOne("AVASphere.ApplicationCore.Sales.Entities.Sale", "Sale")
                        .WithMany("SaleQuotations")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SaleQuotation_Sale_IdSale");

                    b.Navigation("Quotation");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Area", b =>
                {
                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Property", b =>
                {
                    b.Navigation("CatalogValue");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.PropertyValue", b =>
                {
                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Catalogs.Supplier", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.ConfigSys", b =>
                {
                    b.Navigation("ProjectCategories");

                    b.Navigation("Projects");

                    b.Navigation("Quotations");

                    b.Navigation("Sales");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Customer", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Quotations");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.General.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Common.Entities.Products.ProductProperties", b =>
                {
                    b.Navigation("IndividualListingProperties");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.LocationDetails", b =>
                {
                    b.Navigation("PhysicalInventoryDetails");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.PhysicalInventory", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("PhysicalInventoryDetails");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.StorageStructure", b =>
                {
                    b.Navigation("LocationDetails");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.Warehouse", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("PhysicalInventories");

                    b.Navigation("StockMovements");

                    b.Navigation("StorageStructures");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Inventory.Entities.General.WarehouseTransfer", b =>
                {
                    b.Navigation("WarehouseTransferDetails");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.Catalogs.ProjectCategory", b =>
                {
                    b.Navigation("IndividualProjectQuotes");

                    b.Navigation("ListOfCategories");

                    b.Navigation("TechnicalDesigns");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.IndividualProjectQuote", b =>
                {
                    b.Navigation("IndividualListingProperties");

                    b.Navigation("ListOfProductsToQuot");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.Project", b =>
                {
                    b.Navigation("ListOfCategories");

                    b.Navigation("ProjectQuote");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Projects.Entities.General.ProjectQuote", b =>
                {
                    b.Navigation("IndividualProjectQuotes");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Quotation", b =>
                {
                    b.Navigation("SaleQuotations");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AVASphere.ApplicationCore.Sales.Entities.Sale", b =>
                {
                    b.Navigation("SaleQuotations");
                });
#pragma warning restore 612, 618
        }
    }
}
